# Generated by Django 4.0.5 on 2022-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=1030)),
                ('emails', models.CharField(max_length=1030)),
            ],
        ),
    ]
